"""
vfit/export/spice_export.py
───────────────────────────
Export a FosterNetwork (or RationalModel) as a SPICE subcircuit netlist.

Two export modes are available:

1. **Foster ladder** (`mode='foster'`):
   Writes a standard R / L / C netlist from the synthesised element values.
   Requires running `foster_synthesis(model)` first.

2. **Behavioral** (`mode='behavioral'`):
   Writes a Laplace-domain B-source using the rational transfer function
   directly.  Supported by HSPICE, LTspice (with .laplace), Spectre.

Usage
-----
    from vfit.export.spice_export import export_spice_foster, export_spice_behavioral
    export_spice_foster(network, "my_model.cir")
    export_spice_behavioral(model, "my_model_beh.cir")
"""

from __future__ import annotations

import textwrap
from pathlib import Path

import numpy as np

from ..core.rational_function import RationalModel
from ..rlc.rlc_synthesis import FosterNetwork, RLCBranch


# ─────────────────────────────────────────────────────────────────────────────
# Foster Ladder Export
# ─────────────────────────────────────────────────────────────────────────────

def _write_file(path: Path, lines: list[str]) -> None:
    """Write a list of strings to a file, one line each."""
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def export_spice_foster(
    network: FosterNetwork,
    path: str | Path,
    subckt_name: str = "VF_FOSTER",
    port_pos: str = "1",
    port_neg: str = "0",
) -> None:
    """
    Write a SPICE subcircuit for the Foster-I RLC ladder.

    Branches are connected in series (port_pos → Z1 → Z2 → ... → port_neg)
    using internal nodes n0, n1, ...  Each branch element (R/L/C) is placed
    in parallel between the two nodes of that branch segment.

    Parameters
    ----------
    network : FosterNetwork
        Synthesised RLC network from foster_synthesis().
    path : str or Path
        Output file path (e.g. 'model.cir').
    subckt_name : str
        SPICE subcircuit name.
    port_pos, port_neg : str
        Positive and negative port node names.
    """
    path = Path(path)
    lines: list[str] = []

    lines.append(f"* Vector Fitting — Foster-I RLC Subcircuit")
    lines.append(f"* Generated by vfit/export/spice_export.py")
    if network.model is not None:
        m = network.model
        lines.append(f"* Poles: {m.n_poles}   RMS error: {m.rms_error:.3e}")
    lines.append("")
    lines.append(f".SUBCKT {subckt_name} {port_pos} {port_neg}")
    lines.append("")

    elem_counter = {"R": 0, "L": 0, "C": 0}
    branches = network.branches
    n_branches = len(branches)

    # Build a series chain of internal nodes:
    #   port_pos → [branch 0] → n0 → [branch 1] → n1 → ... → port_neg
    def node_name(i: int) -> str:
        """Node after branch i (before branch i+1)."""
        return port_neg if i == n_branches - 1 else f"n{i:04d}"

    prev_node = port_pos
    for idx, branch in enumerate(branches):
        next_node = node_name(idx)
        _write_branch(lines, branch, idx, prev_node, next_node, elem_counter)
        lines.append("")
        prev_node = next_node

    lines.append(f".ENDS {subckt_name}")
    lines.append("")

    _write_file(path, lines)
    print(f"[vfit] SPICE Foster netlist written → {path}")


def _write_branch(
    lines: list[str],
    branch: RLCBranch,
    idx: int,
    node_a: str,
    node_b: str,
    ctr: dict,
) -> None:
    """Append SPICE element lines for one branch."""
    bt = branch.branch_type
    mid = f"nm{idx}"    # internal mid-node when two elements needed

    def next_R() -> str:
        name = f"R{ctr['R']:04d}"
        ctr['R'] += 1
        return name

    def next_L() -> str:
        name = f"L{ctr['L']:04d}"
        ctr['L'] += 1
        return name

    def next_C() -> str:
        name = f"C{ctr['C']:04d}"
        ctr['C'] += 1
        return name

    if bt == "R_only":
        lines.append(f"* Branch {idx}: series resistance (d-term)")
        lines.append(f"{next_R()}   {node_a}  {node_b}  {_fmt(branch.R)}")

    elif bt == "C_only":
        lines.append(f"* Branch {idx}: shunt capacitance (near-DC pole)")
        lines.append(f"{next_C()}   {node_a}  {node_b}  {_fmt(branch.C)}")

    elif bt == "L_only":
        lines.append(f"* Branch {idx}: series inductance (e-term)")
        lines.append(f"{next_L()}   {node_a}  {node_b}  {_fmt(branch.L)}")

    elif bt == "RL":
        # Legacy parallel RL (should not appear in new synthesis)
        # Z = sLR/(sL+R):  R and L in parallel between port nodes
        lines.append(f"* Branch {idx}: parallel RL (legacy)  pole={branch.pole:.4e}")
        lines.append(f"{next_R()}  {node_a} {node_b}  {_fmt(branch.R)}")
        lines.append(f"{next_L()}  {node_a} {node_b}  {_fmt(branch.L)}")

    elif bt == "RC":
        # Parallel RC: Z = R/(1+sRC)
        # Correct topology for a real LHP pole p=-alpha with residue c:
        #   R = c/alpha,   C = 1/c
        # In SPICE: R and C in parallel between port nodes
        lines.append(f"* Branch {idx}: parallel RC  pole={branch.pole:.4e}")
        lines.append(f"* Z = R/(1+sRC),  R={_fmt(branch.R)},  C={_fmt(branch.C)}")
        lines.append(f"{next_R()}  {node_a} {node_b}  {_fmt(branch.R)}")
        lines.append(f"{next_C()}  {node_a} {node_b}  {_fmt(branch.C)}")

    elif bt == "RLC":
        # Parallel RLC: Z = 1/(1/R + 1/(sL) + sC)
        # All three elements in parallel between port nodes
        lines.append(f"* Branch {idx}: parallel RLC  pole={branch.pole:.4e}")
        lines.append(f"* Z = 1/(1/R + 1/sL + sC),  R={_fmt(branch.R)},  L={_fmt(branch.L)},  C={_fmt(branch.C)}")
        lines.append(f"{next_R()}  {node_a} {node_b}  {_fmt(branch.R)}")
        lines.append(f"{next_L()}  {node_a} {node_b}  {_fmt(branch.L)}")
        lines.append(f"{next_C()}  {node_a} {node_b}  {_fmt(branch.C)}")


# ─────────────────────────────────────────────────────────────────────────────
# Behavioral (Laplace) Export
# ─────────────────────────────────────────────────────────────────────────────

def export_spice_behavioral(
    model: RationalModel,
    path: str | Path,
    subckt_name: str = "VF_LAPLACE",
    port_in: str = "in",
    port_out: str = "out",
    port_gnd: str = "0",
) -> None:
    """
    Write an LTspice Laplace behavioral subcircuit for the rational model.

    Uses LTspice E-source LAPLACE syntax::

        E1 out 0 LAPLACE {V(in,0)} = {NUM(s)/DEN(s)}

    where NUM and DEN are polynomials in ascending powers of s.

    The subcircuit has three terminals: in, out, gnd (ground reference).
    Connect as: X1 <in_node> <out_node> 0 <subckt_name>

    Parameters
    ----------
    model : RationalModel
    path : str or Path
    subckt_name : str
    port_in, port_out, port_gnd : str
        Port node names inside the subcircuit definition.
    """
    path = Path(path)

    num_poly, den_poly = _model_to_poly(model)

    # Ascending-power coefficients (a0 + a1*s + a2*s^2 + ...)
    num_coeffs = num_poly[::-1]
    den_coeffs = den_poly[::-1]

    # Normalize by the geometric mean of pole magnitudes so that the
    # polynomial variable sn = s/w0 is of order 1 across the band.
    # Without normalization, s^4 at GHz frequencies reaches ~1e36, causing
    # catastrophic cancellation between terms and wrong LTspice results.
    w0 = _normalization_frequency(model)
    norm_num = np.array([c * w0**i for i, c in enumerate(num_coeffs)])
    norm_den = np.array([c * w0**i for i, c in enumerate(den_coeffs)])

    num_expr = _poly_expr_normalized(norm_num, w0)
    den_expr = _poly_expr_normalized(norm_den, w0)

    lines = [
        f"* Vector Fitting \u2014 Behavioral Laplace Subcircuit (LTspice)",
        f"* Generated by vfit/export/spice_export.py",
        f"* Poles: {model.n_poles}   RMS error: {model.rms_error:.3e}",
        f"* Normalization: w0 = {w0:.6e} rad/s  (sn = s/w0 is order-1 across band)",
        f"",
        f".SUBCKT {subckt_name} {port_in} {port_out} {port_gnd}",
        f"* V({port_out},{port_gnd}) = H(s) * V({port_in},{port_gnd})",
        f"* H(s) = NUM(sn) / DEN(sn),  sn = s / w0",
        f"E1 {port_out} {port_gnd} LAPLACE {{V({port_in},{port_gnd})}} = "
        f"{{({num_expr})/({den_expr})}}",
        f"Rbleed {port_out} {port_gnd} 1G   ; DC path \u2014 prevents floating node warning",
        f"",
        f".ENDS {subckt_name}",
        f"",
    ]

    _write_file(path, lines)
    print(f"[vfit] SPICE behavioral netlist written → {path}")


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _model_to_poly(model: RationalModel):
    """Return (num_poly, den_poly) as numpy coefficient arrays (descending)."""
    poles = model.poles
    residues = model.residues
    n = len(poles)

    den_poly = np.poly(poles).real   # shape (n+1,)

    # Numerator = d * den + Σᵢ cᵢ * Π_{j≠i}(s-pⱼ)
    num_poly = model.d * den_poly.copy()
    for i in range(n):
        other = np.delete(poles, i)
        partial = np.poly(other).real   # shape (n,)
        num_poly[1:] += residues[i].real * partial

    return num_poly, den_poly


def _fmt(val: float) -> str:
    """Format a float in SPICE-friendly scientific notation."""
    if val == 0:
        return "0"
    exp = int(np.floor(np.log10(abs(val))))
    mantissa = val / 10**exp
    # Use SPICE suffix if possible
    suffixes = {12: "T", 9: "G", 6: "MEG", 3: "K",
                0: "", -3: "m", -6: "u", -9: "n", -12: "p", -15: "f"}
    for e, suffix in sorted(suffixes.items(), reverse=True):
        if exp >= e:
            scaled = val / 10**e
            return f"{scaled:.4g}{suffix}"
    return f"{val:.4e}"


def num_str_inline(coeffs: np.ndarray) -> str:
    """Build inline polynomial string for LTspice: a0 + a1*s + a2*s^2 ..."""
    terms = []
    for i, c in enumerate(coeffs.real):
        if abs(c) < 1e-30:
            continue
        if i == 0:
            terms.append(f"{c:.4e}")
        elif i == 1:
            terms.append(f"{c:.4e}*s")
        else:
            terms.append(f"{c:.4e}*s**{i}")
    return " + ".join(terms) if terms else "0"


def _poly_expr(coeffs: np.ndarray) -> str:
    """
    Build a compact LTspice polynomial expression (ascending powers of s).

    Uses the form: c0 + c1*s + c2*s**2 + ...
    Empty terms (|c| < 1e-30) are omitted.
    """
    terms = []
    for i, c in enumerate(coeffs.real):
        if abs(c) < 1e-30:
            continue
        if i == 0:
            terms.append(f"{c:.6e}")
        elif i == 1:
            terms.append(f"{c:.6e}*s")
        else:
            terms.append(f"{c:.6e}*s**{i}")
    return "+".join(terms) if terms else "0"


def _fmt_hz(freq_hz: float) -> str:
    """Format a frequency in Hz as a compact LTspice string (e.g. 1e6 → '1Meg')."""
    if freq_hz >= 1e9:
        v = freq_hz / 1e9
        return f"{v:g}G"
    if freq_hz >= 1e6:
        v = freq_hz / 1e6
        return f"{v:g}Meg"
    if freq_hz >= 1e3:
        v = freq_hz / 1e3
        return f"{v:g}K"
    return f"{freq_hz:g}"


def _normalization_frequency(model: RationalModel) -> float:
    """Geometric mean of pole magnitudes — used to normalize s in LAPLACE export.

    Ensures all polynomial coefficients are order-1, avoiding the catastrophic
    cancellation that occurs when s^n at GHz reaches 1e30+ in double precision.
    """
    mags = np.abs(model.poles)
    return float(np.sqrt(mags.min() * mags.max()))


def _poly_expr_normalized(norm_coeffs: np.ndarray, w0: float) -> str:
    """Build LTspice polynomial in the normalized variable sn = s/w0.

    norm_coeffs[i] = original_coeffs[i] * w0**i, so these are order-1.
    The expression uses (s/<w0>) so LTspice evaluates with sn in-place.
    """
    w0_str = f"{w0:.6e}"
    terms = []
    threshold = max(abs(norm_coeffs.real)) * 1e-14  # relative threshold
    for i, c in enumerate(norm_coeffs.real):
        if abs(c) < threshold:
            continue
        if i == 0:
            terms.append(f"{c:.6e}")
        elif i == 1:
            terms.append(f"{c:.6e}*(s/{w0_str})")
        else:
            terms.append(f"{c:.6e}*(s/{w0_str})**{i}")
    return "+".join(terms) if terms else "0"


def export_spice_test_foster(
    network: FosterNetwork,
    path: str | Path,
    subckt_name: str = "VF_FOSTER",
    subckt_file: str | Path | None = None,
    freq_start_hz: float = 1e6,
    freq_stop_hz: float = 10e9,
) -> None:
    """
    Write a complete LTspice test circuit for the Foster RLC subcircuit.

    Includes AC analysis setup to measure impedance Bode plot.

    Parameters
    ----------
    network : FosterNetwork
    path : str or Path
        Output test circuit file path.
    subckt_name : str
        Name of the subcircuit to instantiate.
    subckt_file : str or Path, optional
        Path to the subcircuit file to include. If None, assumes subcircuit is defined inline.
    freq_start_hz, freq_stop_hz : float
        AC sweep frequency range in Hz (default: 1 MHz – 10 GHz).
    """
    path = Path(path)
    lines: list[str] = []

    f_start = _fmt_hz(freq_start_hz)
    f_stop  = _fmt_hz(freq_stop_hz)

    lines.append("* LTspice test circuit for Foster RLC subcircuit")
    lines.append("* Generated by vfit/export/spice_export.py")
    lines.append("* Run simulation and plot V(1) in Bode format to see impedance Z(s)")
    lines.append("")

    if subckt_file is not None:
        lines.append(f".include {Path(subckt_file).name}")
        lines.append("")

    lines.append("* Voltage source: 1V AC at node 1")
    lines.append("Vin  1 0 AC 1")
    lines.append("")
    lines.append("* Instantiate the subcircuit (port_pos=1, port_neg=0)")
    lines.append(f"X1 1 0 {subckt_name}")
    lines.append("")
    lines.append(f"* AC sweep: 100 points per decade from {f_start} to {f_stop}")
    lines.append(f".ac dec 100 {f_start} {f_stop}")
    lines.append("")
    lines.append(".end")

    _write_file(path, lines)
    print(f"[vfit] LTspice test circuit written → {path}")


def export_spice_test_behavioral(
    model: RationalModel,
    path: str | Path,
    subckt_name: str = "VF_LAPLACE",
    subckt_file: str | Path | None = None,
    freq_start_hz: float = 1e6,
    freq_stop_hz: float = 10e9,
) -> None:
    """
    Write a complete LTspice test circuit for the behavioral Laplace subcircuit.

    Includes AC analysis setup to measure transfer function Bode plot.

    Parameters
    ----------
    model : RationalModel
    path : str or Path
    subckt_name : str
    subckt_file : str or Path, optional
    freq_start_hz, freq_stop_hz : float
        AC sweep frequency range in Hz (default: 1 MHz – 10 GHz).
    """
    path = Path(path)
    lines: list[str] = []

    f_start = _fmt_hz(freq_start_hz)
    f_stop  = _fmt_hz(freq_stop_hz)

    lines.append("* LTspice test circuit for Behavioral Laplace subcircuit")
    lines.append("* Generated by vfit/export/spice_export.py")
    lines.append("* Run simulation and plot V(out) in Bode format to see H(s)")
    lines.append("")

    if subckt_file is not None:
        lines.append(f".include {Path(subckt_file).name}")
        lines.append("")

    lines.append("* Input voltage source (1V AC)")
    lines.append("Vin in 0 AC 1")
    lines.append("")
    lines.append("* Instantiate the subcircuit")
    lines.append(f"X1 in out 0 {subckt_name}")
    lines.append("")
    lines.append(f"* AC sweep: 100 points per decade from {f_start} to {f_stop}")
    lines.append(f".ac dec 100 {f_start} {f_stop}")
    lines.append("")
    lines.append(".end")

    _write_file(path, lines)
    print(f"[vfit] LTspice test circuit written → {path}")
