"""
vfit/export/spice_export.py
───────────────────────────
Export a FosterNetwork (or RationalModel) as a SPICE subcircuit netlist.

Two export modes are available:

1. **Foster ladder** (`mode='foster'`):
   Writes a standard R / L / C netlist from the synthesised element values.
   Requires running `foster_synthesis(model)` first.

2. **Behavioral** (`mode='behavioral'`):
   Writes a Laplace-domain E-source subcircuit using the rational transfer
   function directly.  Uses LTspice-native ``E ... LAPLACE`` syntax:

       E1 out 0 LAPLACE {V(in,0)} = {NUM(s)/DEN(s)}

   Compatible with LTspice XVII and later.  Also works in HSPICE and Spectre
   after minor syntax adaptation.

Usage
-----
    from vfit.export.spice_export import export_spice_foster, export_spice_behavioral
    export_spice_foster(network, "my_model.cir")
    export_spice_behavioral(model, "my_model_beh.cir")
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from ..core.rational_function import RationalModel
from ..rlc.rlc_synthesis import FosterNetwork, RLCBranch

# Branches whose sole element value falls below this threshold are skipped.
# A zero-ohm resistor is a short circuit in SPICE; very-near-zero values are
# numerically degenerate and will cause convergence issues.
_MIN_ELEMENT = 1e-18


# ─────────────────────────────────────────────────────────────────────────────
# Foster Ladder Export
# ─────────────────────────────────────────────────────────────────────────────

def export_spice_foster(
    network: FosterNetwork,
    path: str | Path,
    subckt_name: str = "VF_FOSTER",
    port_pos: str = "1",
    port_neg: str = "0",
) -> None:
    """
    Write a SPICE subcircuit for the Foster-I RLC ladder.

    Each branch is placed in parallel between the two port nodes.
    Internal nodes are labelled ``n<branch_index>``.

    Parameters
    ----------
    network : FosterNetwork
        Synthesised RLC network from foster_synthesis().
    path : str or Path
        Output file path (e.g. 'model.cir').
    subckt_name : str
        SPICE subcircuit name.
    port_pos, port_neg : str
        Positive and negative port node names.
    """
    path = Path(path)
    lines: list[str] = []

    lines.append("* Vector Fitting — Foster-I RLC Subcircuit")
    lines.append("* Generated by vfit/export/spice_export.py")
    if network.model is not None:
        m = network.model
        lines.append(f"* Poles: {m.n_poles}   RMS error: {m.rms_error:.3e}")
    lines.append("")
    lines.append(f".SUBCKT {subckt_name} {port_pos} {port_neg}")
    lines.append("")

    elem_counter = {"R": 0, "L": 0, "C": 0}

    # Foster-I is a SERIES chain: port_pos → n0 → n1 → ... → port_neg
    # Each branch (parallel RLC / L / R) occupies one link in the chain.
    n_branches = len(network.branches)
    nodes = [port_pos] + [f"n{k}" for k in range(n_branches - 1)] + [port_neg]

    for idx, branch in enumerate(network.branches):
        node_a = nodes[idx]
        node_b = nodes[idx + 1]
        _write_branch(lines, branch, idx, node_a, node_b, elem_counter)

    lines.append(f".ENDS {subckt_name}")
    lines.append("")

    _write_file(path, lines)
    print(f"[vfit] SPICE Foster netlist written → {path}")


def _write_branch(
    lines: list[str],
    branch: RLCBranch,
    idx: int,
    node_a: str,
    node_b: str,
    ctr: dict,
) -> None:
    """Append SPICE element lines for one branch."""
    bt = branch.branch_type

    def next_R() -> str:
        name = f"R{ctr['R']:04d}"
        ctr['R'] += 1
        return name

    def next_L() -> str:
        name = f"L{ctr['L']:04d}"
        ctr['L'] += 1
        return name

    def next_C() -> str:
        name = f"C{ctr['C']:04d}"
        ctr['C'] += 1
        return name

    if bt == "R_only":
        if branch.R is None or abs(branch.R) < _MIN_ELEMENT:
            lines.append(f"* Branch {idx}: R_only skipped (R={branch.R} — zero direct term)")
            lines.append("")
            return
        lines.append(f"{next_R()}   {node_a}  {node_b}  {_fmt(branch.R)}")
        lines.append("")

    elif bt == "C_only":
        if branch.C is None or abs(branch.C) < _MIN_ELEMENT:
            lines.append(f"* Branch {idx}: C_only skipped (C={branch.C} — degenerate)")
            lines.append("")
            return
        lines.append(f"{next_C()}   {node_a}  {node_b}  {_fmt(branch.C)}")
        lines.append("")

    elif bt == "L_only":
        if branch.L is None or abs(branch.L) < _MIN_ELEMENT:
            lines.append(f"* Branch {idx}: L_only skipped (L={branch.L} — degenerate)")
            lines.append("")
            return
        lines.append(f"{next_L()}   {node_a}  {node_b}  {_fmt(branch.L)}")
        lines.append("")

    elif bt == "RL":
        lines.append(f"* Branch {idx}: parallel RL  pole={branch.pole:.4e}")
        if branch.R is not None and abs(branch.R) >= _MIN_ELEMENT:
            lines.append(f"{next_R()}  {node_a} {node_b}  {_fmt(branch.R)}")
        if branch.L is not None and abs(branch.L) >= _MIN_ELEMENT:
            lines.append(f"{next_L()}  {node_a} {node_b}  {_fmt(branch.L)}")
        lines.append("")

    elif bt == "RC":
        lines.append(f"* Branch {idx}: parallel RC  pole={branch.pole:.4e}")
        if branch.R is not None and abs(branch.R) >= _MIN_ELEMENT:
            lines.append(f"{next_R()}  {node_a} {node_b}  {_fmt(branch.R)}")
        if branch.C is not None and abs(branch.C) >= _MIN_ELEMENT:
            lines.append(f"{next_C()}  {node_a} {node_b}  {_fmt(branch.C)}")
        lines.append("")

    elif bt == "RLC":
        lines.append(f"* Branch {idx}: parallel RLC  pole={branch.pole:.4e}")
        if branch.R is not None and abs(branch.R) >= _MIN_ELEMENT:
            lines.append(f"{next_R()}  {node_a} {node_b}  {_fmt(branch.R)}")
        if branch.L is not None and abs(branch.L) >= _MIN_ELEMENT:
            lines.append(f"{next_L()}  {node_a} {node_b}  {_fmt(branch.L)}")
        else:
            lines.append(f"* L skipped — degenerate value ({branch.L})")
        if branch.C is not None and abs(branch.C) >= _MIN_ELEMENT:
            lines.append(f"{next_C()}  {node_a} {node_b}  {_fmt(branch.C)}")
        lines.append("")


# ─────────────────────────────────────────────────────────────────────────────
# Behavioral (Laplace) Export — LTspice compatible
# ─────────────────────────────────────────────────────────────────────────────

def export_spice_behavioral(
    model: RationalModel,
    path: str | Path,
    subckt_name: str = "VF_LAPLACE",
    port_in: str = "in",
    port_out: str = "out",
    port_ref: str = "0",
) -> None:
    """
    Write a LTspice-compatible Laplace behavioral subcircuit.

    The subcircuit has three ports: ``port_in``, ``port_out``, and
    ``port_ref`` (reference / ground).  The E-source implements:

        V(port_out, port_ref) = H(s) * V(port_in, port_ref)

    where H(s) = NUM(s) / DEN(s) is the rational transfer function.

    Instantiation in LTspice::

        X1 sig_in sig_out GND VF_LAPLACE

    Compatible with LTspice XVII.  For HSPICE / Spectre adapt the
    ``E ... LAPLACE`` line to the respective simulator's syntax.

    Parameters
    ----------
    model : RationalModel
        Fitted rational function model.
    path : str or Path
        Output file path (e.g. 'model.cir').
    subckt_name : str
        SPICE subcircuit name.
    port_in, port_out, port_ref : str
        Node names for the input, output, and reference pins.
    """
    path = Path(path)

    # Build numerator and denominator polynomials (ascending power order)
    num_poly, den_poly = _model_to_poly(model)
    num_coeffs = num_poly[::-1]   # np.poly gives descending; flip to ascending
    den_coeffs = den_poly[::-1]

    num_expr = _poly_str_ltspice(num_coeffs)
    den_expr = _poly_str_ltspice(den_coeffs)

    lines = [
        "* Vector Fitting — Behavioral Laplace Subcircuit (LTspice)",
        "* Generated by vfit/export/spice_export.py",
        f"* Poles: {model.n_poles}   RMS error: {model.rms_error:.3e}",
        "",
        f".SUBCKT {subckt_name} {port_in} {port_out} {port_ref}",
        f"* V({port_out},{port_ref}) = H(s) * V({port_in},{port_ref})",
        "* H(s) = NUM(s) / DEN(s)",
        (
            f"E1 {port_out} {port_ref} LAPLACE "
            f"{{V({port_in},{port_ref})}} = "
            f"{{({num_expr})/({den_expr})}}"
        ),
        "",
        f".ENDS {subckt_name}",
        "",
    ]

    _write_file(path, lines)
    print(f"[vfit] SPICE behavioral netlist written → {path}")


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _model_to_poly(model: RationalModel):
    """Return (num_poly, den_poly) as numpy coefficient arrays (descending)."""
    poles = model.poles
    residues = model.residues
    n = len(poles)

    den_poly = np.poly(poles).real   # shape (n+1,)

    # Numerator = d * den + Σᵢ cᵢ * Π_{j≠i}(s-pⱼ)
    num_poly = model.d * den_poly.copy()
    for i in range(n):
        other = np.delete(poles, i)
        partial = np.poly(other).real   # shape (n,)
        num_poly[1:] += residues[i].real * partial

    return num_poly, den_poly


def _poly_str_ltspice(coeffs: np.ndarray) -> str:
    """
    Build a polynomial string for LTspice LAPLACE syntax.

    Coefficients are in ascending power order (a0, a1, a2, ...) and the
    result uses LTspice exponentiation notation ``s^N`` (not ``s**N``).

    Examples
    --------
    >>> _poly_str_ltspice(np.array([3.0, -2.0, 1.0]))
    '3.000000e+00-2.000000e+00*s+1.000000e+00*s^2'
    """
    terms: list[str] = []
    for i, c in enumerate(coeffs.real):
        if abs(c) < 1e-30:
            continue
        if i == 0:
            terms.append(f"{c:.6e}")
        elif i == 1:
            terms.append(f"{c:.6e}*s")
        else:
            terms.append(f"{c:.6e}*s^{i}")

    if not terms:
        return "0"

    # Join terms: avoid "+-" double signs by checking leading character
    result = terms[0]
    for t in terms[1:]:
        result += t if t.startswith("-") else "+" + t
    return result


def _fmt(val: float) -> str:
    """Format a float in SPICE-friendly scientific notation."""
    if val == 0:
        return "0"
    exp = int(np.floor(np.log10(abs(val))))
    suffixes = {12: "T", 9: "G", 6: "MEG", 3: "K",
                0: "", -3: "m", -6: "u", -9: "n", -12: "p", -15: "f"}
    for e, suffix in sorted(suffixes.items(), reverse=True):
        if exp >= e:
            scaled = val / 10**e
            return f"{scaled:.4g}{suffix}"
    return f"{val:.4e}"


def _write_file(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
