"""
vfit/export/spice_export.py
───────────────────────────
Export a FosterNetwork (or RationalModel) as a SPICE subcircuit netlist.

Two export modes are available:

1. **Foster ladder** (`mode='foster'`):
   Writes a standard R / L / C netlist from the synthesised element values.
   Requires running `foster_synthesis(model)` first.

2. **Behavioral** (`mode='behavioral'`):
   Writes a Laplace-domain B-source using the rational transfer function
   directly.  Supported by HSPICE, LTspice (with .laplace), Spectre.

Usage
-----
    from vfit.export.spice_export import export_spice_foster, export_spice_behavioral
    export_spice_foster(network, "my_model.cir")
    export_spice_behavioral(model, "my_model_beh.cir")
"""

from __future__ import annotations

import textwrap
from pathlib import Path

import numpy as np

from ..core.rational_function import RationalModel
from ..rlc.rlc_synthesis import FosterNetwork, RLCBranch


# ─────────────────────────────────────────────────────────────────────────────
# Foster Ladder Export
# ─────────────────────────────────────────────────────────────────────────────

def export_spice_foster(
    network: FosterNetwork,
    path: str | Path,
    subckt_name: str = "VF_FOSTER",
    port_pos: str = "1",
    port_neg: str = "0",
) -> None:
    """
    Write a SPICE subcircuit for the Foster-I RLC ladder.

    Each branch is placed in parallel between the two port nodes.
    Internal nodes are labelled ``n<branch_index>``.

    Parameters
    ----------
    network : FosterNetwork
        Synthesised RLC network from foster_synthesis().
    path : str or Path
        Output file path (e.g. 'model.cir').
    subckt_name : str
        SPICE subcircuit name.
    port_pos, port_neg : str
        Positive and negative port node names.
    """
    path = Path(path)
    lines: list[str] = []

    lines.append(f"* Vector Fitting — Foster-I RLC Subcircuit")
    lines.append(f"* Generated by vfit/export/spice_export.py")
    if network.model is not None:
        m = network.model
        lines.append(f"* Poles: {m.n_poles}   RMS error: {m.rms_error:.3e}")
    lines.append("")
    lines.append(f".SUBCKT {subckt_name} {port_pos} {port_neg}")
    lines.append("")

    elem_counter = {"R": 0, "L": 0, "C": 0}

    for idx, branch in enumerate(network.branches):
        node_a = port_pos
        node_b = port_neg
        _write_branch(lines, branch, idx, node_a, node_b, elem_counter)
        lines.append("")

    lines.append(f".ENDS {subckt_name}")
    lines.append("")

    _write_file(path, lines)
    print(f"[vfit] SPICE Foster netlist written → {path}")


def _write_branch(
    lines: list[str],
    branch: RLCBranch,
    idx: int,
    node_a: str,
    node_b: str,
    ctr: dict,
) -> None:
    """Append SPICE element lines for one branch."""
    bt = branch.branch_type
    mid = f"nm{idx}"    # internal mid-node when two elements needed

    def next_R() -> str:
        name = f"R{ctr['R']:04d}"
        ctr['R'] += 1
        return name

    def next_L() -> str:
        name = f"L{ctr['L']:04d}"
        ctr['L'] += 1
        return name

    def next_C() -> str:
        name = f"C{ctr['C']:04d}"
        ctr['C'] += 1
        return name

    if bt == "R_only":
        lines.append(f"{next_R()}   {node_a}  {node_b}  {_fmt(branch.R)}")

    elif bt == "C_only":
        lines.append(f"{next_C()}   {node_a}  {node_b}  {_fmt(branch.C)}")

    elif bt == "L_only":
        lines.append(f"{next_L()}   {node_a}  {node_b}  {_fmt(branch.L)}")

    elif bt == "RL":
        # Parallel RL: both R and L connect directly between port nodes
        lines.append(f"* Branch {idx}: parallel RL  pole={branch.pole:.4e}")
        lines.append(f"{next_R()}  {node_a} {node_b}  {_fmt(branch.R)}")
        lines.append(f"{next_L()}  {node_a} {node_b}  {_fmt(branch.L)}")

    elif bt == "RC":
        lines.append(f"* Branch {idx}: parallel RC  pole={branch.pole:.4e}")
        lines.append(f"{next_R()}  {node_a} {node_b}  {_fmt(branch.R)}")
        lines.append(f"{next_C()}  {node_a} {node_b}  {_fmt(branch.C)}")

    elif bt == "RLC":
        lines.append(f"* Branch {idx}: parallel RLC  pole={branch.pole:.4e}")
        lines.append(f"{next_R()}  {node_a} {node_b}  {_fmt(branch.R)}")
        lines.append(f"{next_L()}  {node_a} {node_b}  {_fmt(branch.L)}")
        lines.append(f"{next_C()}  {node_a} {node_b}  {_fmt(branch.C)}")


# ─────────────────────────────────────────────────────────────────────────────
# Behavioral (Laplace) Export
# ─────────────────────────────────────────────────────────────────────────────

def export_spice_behavioral(
    model: RationalModel,
    path: str | Path,
    subckt_name: str = "VF_LAPLACE",
    port_pos: str = "1",
    port_neg: str = "0",
) -> None:
    """
    Write a SPICE Laplace behavioral source for the rational model.

    Uses the numerator / denominator polynomial representation:

        H(s) = (b₀ + b₁s + b₂s² + ...)
               ─────────────────────────
               (a₀ + a₁s + a₂s² + ...)

    Syntax is compatible with HSPICE / Spectre `laplace` source.
    LTspice users should use a `B` source with {laplace=...}.

    Parameters
    ----------
    model : RationalModel
    path : str or Path
    subckt_name, port_pos, port_neg : str
    """
    path = Path(path)

    # Build numerator and denominator polynomials
    num_poly, den_poly = _model_to_poly(model)

    # Coefficients in ascending power (SPICE convention: a0 + a1*s + a2*s^2 ...)
    num_coeffs = num_poly[::-1]   # np.poly gives descending order
    den_coeffs = den_poly[::-1]

    num_str = " ".join(f"{c:.6e}" for c in num_coeffs.real)
    den_str = " ".join(f"{c:.6e}" for c in den_coeffs.real)

    lines = [
        f"* Vector Fitting — Behavioral Laplace Subcircuit",
        f"* Generated by vfit/export/spice_export.py",
        f"* Poles: {model.n_poles}   RMS error: {model.rms_error:.3e}",
        f"",
        f".SUBCKT {subckt_name} {port_pos} {port_neg}",
        f"* Laplace transfer function: H(s) = NUM(s)/DEN(s)",
        f"* NUM coefficients (a0, a1, a2, ...): {num_str}",
        f"* DEN coefficients (b0, b1, b2, ...): {den_str}",
        f"",
        f"* HSPICE syntax:",
        f"Vout_probe {port_pos} {port_neg} DC 0",
        f"B_laplace {port_pos} {port_neg} V = {{laplace(v({port_pos},{port_neg}))={{",
        f"+ numer=[{num_str}]",
        f"+ denom=[{den_str}]}}}}",
        f"",
        f".ENDS {subckt_name}",
        f"",
        f"* ---- LTspice equivalent ----",
        f"* .param s={{2*pi*i*frequency}}",
        f"* B1 out 0 V = (({num_str_inline(num_coeffs)})/({num_str_inline(den_coeffs)}))",
    ]

    _write_file(path, lines)
    print(f"[vfit] SPICE behavioral netlist written → {path}")


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _model_to_poly(model: RationalModel):
    """Return (num_poly, den_poly) as numpy coefficient arrays (descending)."""
    poles = model.poles
    residues = model.residues
    n = len(poles)

    den_poly = np.poly(poles).real   # shape (n+1,)

    # Numerator = d * den + Σᵢ cᵢ * Π_{j≠i}(s-pⱼ)
    num_poly = model.d * den_poly.copy()
    for i in range(n):
        other = np.delete(poles, i)
        partial = np.poly(other).real   # shape (n,)
        num_poly[1:] += residues[i].real * partial

    return num_poly, den_poly


def _fmt(val: float) -> str:
    """Format a float in SPICE-friendly scientific notation."""
    if val == 0:
        return "0"
    exp = int(np.floor(np.log10(abs(val))))
    mantissa = val / 10**exp
    # Use SPICE suffix if possible
    suffixes = {12: "T", 9: "G", 6: "MEG", 3: "K",
                0: "", -3: "m", -6: "u", -9: "n", -12: "p", -15: "f"}
    for e, suffix in sorted(suffixes.items(), reverse=True):
        if exp >= e:
            scaled = val / 10**e
            return f"{scaled:.4g}{suffix}"
    return f"{val:.4e}"


def num_str_inline(coeffs: np.ndarray) -> str:
    """Build inline polynomial string for LTspice: a0 + a1*s + a2*s^2 ..."""
    terms = []
    for i, c in enumerate(coeffs.real):
        if abs(c) < 1e-30:
            continue
        if i == 0:
            terms.append(f"{c:.4e}")
        elif i == 1:
            terms.append(f"{c:.4e}*s")
        else:
            terms.append(f"{c:.4e}*s**{i}")
    return " + ".join(terms) if terms else "0"


def _write_file(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
